edition = "2021"
array_width = 100
blank_lines_upper_bound = 2
chain_width = 100
comment_width = 100
condense_wildcard_suffixes = true
fn_call_width = 100
group_imports = "StdExternalCrate"
imports_layout = "Vertical"
imports_granularity = "Module"
match_block_trailing_comma = true
max_width = 120
newline_style = "Unix"
reorder_impl_items = true
single_line_if_else_max_width = 100
struct_lit_width = 50
use_field_init_shorthand = true
wrap_comments = true
