apiVersion: v1
kind: ServiceAccount
metadata:
  name: sk-ctrl-sa
  namespace: simkube
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: sk-ctrl-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: sk-ctrl-sa
    namespace: simkube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: sk-ctrl
  name: sk-ctrl-depl
  namespace: simkube
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: sk-ctrl
  template:
    metadata:
      labels:
        app.kubernetes.io/name: sk-ctrl
    spec:
      containers:
        - args:
            - /sk-ctrl
            - --use-cert-manager
            - --cert-manager-issuer
            - selfsigned
          env:
            - name: RUST_BACKTRACE
              value: "1"
            - name: POD_SVC_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
            - name: CTRL_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_OWNER
              value: sk-ctrl-depl
          image: quay.io/appliedcomputing/sk-ctrl:v0.10.1
          name: sk-ctrl
      nodeSelector:
        type: kind-worker
      serviceAccountName: sk-ctrl-sa
