---
nav:
  - Getting Started:
      - Concepts: docs/intro/concepts.md
      - Installation: docs/intro/installation.md
      - Running a Simulation: docs/intro/running.md
  - Advanced:
      - Configuration: docs/adv/config.md
      - Autoscaling: docs/adv/autoscaling.md
      - Collecting Metrics: docs/adv/metrics.md
      - Traces: docs/adv/traces.md
      - Hooks: docs/adv/hooks.md
  - Components:
      - skctl: docs/components/skctl.md
      - sk-ctrl: docs/components/sk-ctrl.md
      - sk-driver: docs/components/sk-driver.md
      - sk-tracer: docs/components/sk-tracer.md
  - Infrastructure:
      - Overview: docs/infra/overview.md
      - Amazon Machine Images (AMI's): docs/infra/amis.md
      - Using SimKube AMIs: docs/infra/usage.md
      - Custom GithHub Action Runners: docs/infra/github-runners.md
  - Contributing:
      - Setting up: docs/dev/setup.md
      - Developer's Guide: docs/dev/contributing.md
      - API changes: docs/dev/api_changes.md
  - Reference:
      - CRDs: docs/ref/crds.md
