---
nav:
  - Getting Started:
      - Concepts: docs/intro/concepts.md
      - Installation: docs/intro/installation.md
      - Running a Simulation: docs/intro/running.md
  - Advanced:
      - Configuration: docs/adv/config.md
      - Autoscaling: docs/adv/autoscaling.md
      - Collecting Metrics: docs/adv/metrics.md
      - Traces: docs/adv/traces.md
      - Hooks: docs/adv/hooks.md
  - SKEL:
      - Introduction: docs/skel/intro.md
      - Usage: docs/skel/usage.md
  - Components:
      - skctl: docs/components/skctl.md
      - sk-ctrl: docs/components/sk-ctrl.md
      - sk-driver: docs/components/sk-driver.md
      - sk-tracer: docs/components/sk-tracer.md
  - Prebuilt Simulation Environments:
      - Overview: docs/infra/overview.md
      - SimKube AMIs: docs/infra/amis.md
      - Using SimKube AMIs: docs/infra/usage.md
      - GithHub Action Runners: docs/infra/github-runners.md
      - Evaluating Results: docs/infra/evaluate.md
      - Troubleshooting: docs/infra/troubleshooting.md
  - Contributing:
      - Setting up: docs/dev/setup.md
      - Developer's Guide: docs/dev/contributing.md
      - API changes: docs/dev/api_changes.md
  - Reference:
      - CRDs: docs/ref/crds.md
      - SimKube Trace Format: docs/ref/trace-files.md
      - SKEL reference: docs/ref/skel.md
