---
name: Compute k8s plan

on:  # yamllint disable-line rule:truthy
  pull_request:
    paths:
      - "k8s/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  plan:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main
        uses: actions/checkout@v4
        with:
          ref: main
          submodules: recursive

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Compile k8s charts
        run: make k8s

      - name: Check out PR
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Compute dag/diff
        run: make k8s

      - name: Save artifacts
        run: |
          mkdir -p ./artifacts
          echo ${{ github.event.number }} > ./artifacts/PR
          mv .build/dag.mermaid ./artifacts/dag.mermaid
          mv .build/k8s.df ./artifacts/k8s.df

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: k8s-plan-artifacts
          path: artifacts/
